"""Agregar campos PMI a proyectos

Revision ID: 21f59b5ff705
Revises: 
Create Date: 2026-01-08 21:41:36.998580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '21f59b5ff705'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_informes_estado', table_name='informes')
    op.drop_index('ix_informes_id', table_name='informes')
    op.drop_index('ix_informes_titulo', table_name='informes')
    op.drop_table('informes')
    op.create_index(op.f('ix_clientes_activo'), 'clientes', ['activo'], unique=False)
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=False)
    op.create_index(op.f('ix_clientes_industria'), 'clientes', ['industria'], unique=False)
    op.create_index(op.f('ix_clientes_tipo_cliente'), 'clientes', ['tipo_cliente'], unique=False)
    op.drop_column('cotizaciones', 'cliente_id')
    op.add_column('proyectos', sa.Column('servicio', sa.String(length=50), nullable=True))
    op.add_column('proyectos', sa.Column('industria', sa.String(length=50), nullable=True))
    op.add_column('proyectos', sa.Column('presupuesto', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('proyectos', sa.Column('moneda', sa.String(length=3), nullable=True))
    op.add_column('proyectos', sa.Column('duracion_total', sa.Integer(), nullable=True))
    op.add_column('proyectos', sa.Column('tipo_dias', sa.String(length=20), nullable=True))
    op.add_column('proyectos', sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('proyectos', sa.Column('tiene_area', sa.Boolean(), nullable=True))
    op.add_column('proyectos', sa.Column('alcance_proyecto', sa.Text(), nullable=True))
    op.add_column('proyectos', sa.Column('ubicacion', sa.String(length=200), nullable=True))
    op.add_column('proyectos', sa.Column('normativa', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_proyectos_industria'), 'proyectos', ['industria'], unique=False)
    op.create_index(op.f('ix_proyectos_servicio'), 'proyectos', ['servicio'], unique=False)
    op.drop_column('proyectos', 'cliente_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('cliente_id', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_proyectos_servicio'), table_name='proyectos')
    op.drop_index(op.f('ix_proyectos_industria'), table_name='proyectos')
    op.drop_column('proyectos', 'normativa')
    op.drop_column('proyectos', 'ubicacion')
    op.drop_column('proyectos', 'alcance_proyecto')
    op.drop_column('proyectos', 'tiene_area')
    op.drop_column('proyectos', 'area_m2')
    op.drop_column('proyectos', 'tipo_dias')
    op.drop_column('proyectos', 'duracion_total')
    op.drop_column('proyectos', 'moneda')
    op.drop_column('proyectos', 'presupuesto')
    op.drop_column('proyectos', 'industria')
    op.drop_column('proyectos', 'servicio')
    op.add_column('cotizaciones', sa.Column('cliente_id', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_clientes_tipo_cliente'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_industria'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_activo'), table_name='clientes')
    op.create_table('informes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=200), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=9), nullable=False),
    sa.Column('formato', sa.VARCHAR(length=4), nullable=False),
    sa.Column('contenido', sa.TEXT(), nullable=True),
    sa.Column('resumen_ejecutivo', sa.TEXT(), nullable=True),
    sa.Column('conclusiones', sa.TEXT(), nullable=True),
    sa.Column('recomendaciones', sa.TEXT(), nullable=True),
    sa.Column('proyecto_id', sa.INTEGER(), nullable=True),
    sa.Column('incluir_graficos', sqlite.JSON(), nullable=True),
    sa.Column('incluir_tablas', sqlite.JSON(), nullable=True),
    sa.Column('metadata_adicional', sqlite.JSON(), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('fecha_modificacion', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_informes_titulo', 'informes', ['titulo'], unique=False)
    op.create_index('ix_informes_id', 'informes', ['id'], unique=False)
    op.create_index('ix_informes_estado', 'informes', ['estado'], unique=False)
    # ### end Alembic commands ###
